### ISSUE TITLE
Compatibility issue for macOS 10.11

### ISSUE THREAD

**Issue by xingheng** [yulingtianxia/pbxprojHelper#1]
Could you please update the project deployment target as 10.11 as minimal version if possible? Some cocoa developers are still there, Thanks!

**Comment by yulingtianxia** [comment]
@xingheng I'm so sorry that some APIs of Swift 3 only support macOS 10.12. They are new structures.

**Comment by skyline75489** [comment]
啥，原来不支持 10.11 ？刚想下载试验一下呢...

**Comment by yulingtianxia** [comment]
@skyline75489 如果用 Objective-C 写，能支持到10.10，但是用了 Swift3 的一些类之后就只能从 10.12起步了。理论上这些类都可以用 NS 开头的 CocoaTouch API 替代，但为了更加 Swifty，只好牺牲了。

**Comment by yulingtianxia** [comment]
@xingheng @skyline75489 Command Line Tool can support macOS 10.10, please try it: https://github.com/yulingtianxia/pbxprojHelper/releases/tag/1.1.1

**Comment by xingheng** [comment]
Confirmed, thanks for your work!
