### ISSUE TITLE
我认真的看了一遍readme，还是看不懂这个软件到底是干嘛用的

### ISSUE THREAD

**Issue by suifengqjn** [yulingtianxia/pbxprojHelper#7]

**Comment by yulingtianxia** [comment]
可以参考下这两篇文章
[pbxprojHelper--Xcode工程文件助手](http://yulingtianxia.com/blog/2016/11/28/pbxprojHelper/)

[Let's Talk About project.pbxproj](http://yulingtianxia.com/blog/2016/09/28/Let-s-Talk-About-project-pbxproj/)
